// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlgxogrwjaedqghwpqaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sZ3hvZ3J3amFlZHFnaHdwcWF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMjcxOTksImV4cCI6MjA1NzgwMzE5OX0.n9eixfOsELXcrzSSHoTuS3KF4kduYVpxkqhC5jzIu7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);